name: signalr
description: Flutter plugin to support .NET SignalR for iOS and Android
version: 0.0.2
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.signalr
        pluginClass: SignalrPlugin
      ios:
        pluginClass: SignalrPlugin

